name: Upload Python Package to PyPI

on:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  publish-to-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/wizardcalls
    permissions:
      id-token: write
    steps:
      - name: Get latest commit
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch wheel build
      - name: Build package
        run: |
          python -m build 
      - name: Publish package to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1